In [1]:
from sympy import *
x ,y, z = symbols ("x y z")

In [2]:
f=x**2-x-21
diff(f,x)

2*x - 1

In [3]:
p=(x-y)**2
diff(p,x)

2*x - 2*y

In [12]:
w, b, y_true, n= symbols ("w b y_true n")
y_pred=w*x +b
diff (((y_true-y_pred)**2)/n,w )
#diff (e, w, b)

-2*x*(-b - w*x + y_true)/n

In [13]:
def part_diff(e) :
    return diff (e, w), diff (e,b )

In [15]:
e= ((y_true-y_pred)**2)/n
dw,db = part_diff(e)
print (dw , db)

-2*x*(-b - w*x + y_true)/n (2*b + 2*w*x - 2*y_true)/n


In [28]:
import numpy as np

class Gradient:
    def __init__(self, X, Y) :
        self.X= X
        self.Y= Y
        
    def predict (self, w, b) :
        return self.X*w +b
    
    def mse (self, Y_pred) :
        MSE = np.square(np.subtract(self.Y, Y_pred)).mean()
        return MSE
    

In [36]:
X= np.arange ( 10)
Y= np.arange (0, 20,2)
print (X)
print (Y)
grad=Gradient (X,Y)
y_pred=grad.predict(2,1)
print (y_pred)
ms=grad.mse(y_pred)
print (ms)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
1.0
